name: Build & Deploy Spring app

on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: Build and Deploy Employees Manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Units Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean package DskipTests --file pom.xml
          mvn -B package --file pom.xml



